Update action.yml

diff --git a/playwright-action/action.yml b/playwright-action/action.yml
--- a/playwright-action/action.yml
+++ b/playwright-action/action.yml
@@ -38,35 +38,33 @@ runs:
           --env-file ${{ inputs.env_file }} \
           -v ${LOCAL_FOLDER}/work/watcher/watcher:/e2e \
           -w /e2e \
-          mcr.microsoft.com/playwright:v1.51.1 \
-          --browser  firefox \
-          --headless || true
-        # POST ACTIONS
-        docker logs ${RUNNER_NAME}-playwright | ansi2html > /tmp/runner/work/playwright_save/log.html
-        docker logs ${RUNNER_NAME}-playwright > /tmp/runner/work/playwright_save/log.txt
-        # python3 getmsg.py /tmp/runner/work/playwright_save/log.txt > /tmp/runner/work/playwright_save/failing_flow.txt || true
-        cp -r ./playwright/screenshots/ /tmp/runner/work/playwright_save/ || true
-        echo "====playwright====="
-        ls ./playwright/**
+          mcr.microsoft.com/playwright:v1.51.1 || true
+        # # POST ACTIONS
+        # docker logs ${RUNNER_NAME}-playwright | ansi2html > /tmp/runner/work/playwright_save/log.html
+        # docker logs ${RUNNER_NAME}-playwright > /tmp/runner/work/playwright_save/log.txt
+        # # python3 getmsg.py /tmp/runner/work/playwright_save/log.txt > /tmp/runner/work/playwright_save/failing_flow.txt || true
+        # #cp -r ./playwright/screenshots/ /tmp/runner/work/playwright_save/ || true
+        # echo "====playwright====="
+        # ls ./playwright/**
         
-        # Find files with commas and rename them
-        find "/tmp/runner/work/playwright_save/" -type f -name "*,*" | while read -r file; do
-            # Get the directory and filename
-            dir=$(dirname "$file")
-            base=$(basename "$file")
+        # # Find files with commas and rename them
+        # find "/tmp/runner/work/playwright_save/" -type f -name "*,*" | while read -r file; do
+        #     # Get the directory and filename
+        #     dir=$(dirname "$file")
+        #     base=$(basename "$file")
               
-            # Replace commas with underscores in the filename
-            new_base=$(echo "$base" | sed 's/,/_/g')
+        #     # Replace commas with underscores in the filename
+        #     new_base=$(echo "$base" | sed 's/,/_/g')
               
-            # Rename the file
-            mv "$file" "$dir/$new_base"
-        done
+        #     # Rename the file
+        #     mv "$file" "$dir/$new_base"
+        # done
         
-        echo "====save====="
-        ls /tmp/runner/work/playwright_save/**
-        EXIT=$(docker inspect ${RUNNER_NAME}-playwright --format='{{.State.ExitCode}}')
-        if [ "$EXIT" != "0" ]; then
-          exit 1
-        else
-          exit 0
-        fi
+        # echo "====save====="
+        # ls /tmp/runner/work/playwright_save/**
+        # EXIT=$(docker inspect ${RUNNER_NAME}-playwright --format='{{.State.ExitCode}}')
+        # if [ "$EXIT" != "0" ]; then
+        #   exit 1
+        # else
+        #   exit 0
+        # fi
