Update action.yml

diff --git a/playwright-action/action.yml b/playwright-action/action.yml
--- a/playwright-action/action.yml
+++ b/playwright-action/action.yml
@@ -43,11 +43,11 @@ runs:
           mcr.microsoft.com/playwright:v1.51.1 \
           npm run test || true
         
-        # # POST ACTIONS
+        # POST ACTIONS
         # docker logs ${RUNNER_NAME}-playwright | ansi2html > /tmp/runner/work/playwright_save/log.html
         # docker logs ${RUNNER_NAME}-playwright > /tmp/runner/work/playwright_save/log.txt
-        # # python3 getmsg.py /tmp/runner/work/playwright_save/log.txt > /tmp/runner/work/playwright_save/failing_flow.txt || true
-        # #cp -r ./playwright/screenshots/ /tmp/runner/work/playwright_save/ || true
+        # python3 getmsg.py /tmp/runner/work/playwright_save/log.txt > /tmp/runner/work/playwright_save/failing_flow.txt || true
+        # cp -r ./playwright/screenshots/ /tmp/runner/work/playwright_save/ || true
         # echo "====playwright====="
         # ls ./playwright/**
         
@@ -66,9 +66,10 @@ runs:
         
         # echo "====save====="
         # ls /tmp/runner/work/playwright_save/**
-        # EXIT=$(docker inspect ${RUNNER_NAME}-playwright --format='{{.State.ExitCode}}')
-        # if [ "$EXIT" != "0" ]; then
-        #   exit 1
-        # else
-        #   exit 0
-        # fi
+        
+        EXIT=$(docker inspect ${RUNNER_NAME}-playwright --format='{{.State.ExitCode}}')
+        if [ "$EXIT" != "0" ]; then
+          exit 1
+        else
+          exit 0
+        fi
